the_weather = ["Wind's howling...", 
"Light rain gently starts showering the platform.", 
"Heavy rain starts drumming on the ballast. Get cover!", 
"A warm fog coats the landscape.", 
"There's a cloud that looks like a squirrel in the sky. Or is it a cow?",
"The clouds are low and moving fast.",
"A bank of clouds is building to the northeast...",
"Muffled sounds of a storm is heard from the sky above the city...",
"There's a double rainbow above the platform... (All the way!)",
"There's a double rainbow above the platform... (Not all the way...)",
"The campfire crackles in delightful bursts...",
"The flame of the campfire dances playfully...",
"Small birds are singing softly from the wires above the platform...",
"A songbird plays a tune and it sounds like silver..."]